#define TOP_PHOTO_TRANSISTOR 6
#define BOTTOM_PHOTO_TRANSISTOR 5

#define TOP_IR_PIN      42
#define BOTTOM_IR_PIN   41

#define LEFT_MOTOR_PIN GPIO_NUM_37
#define RIGHT_MOTOR_PIN GPIO_NUM_1

#define LEFT_MOTOR_CHANNEL RMT_CHANNEL_2
#define RIGHT_MOTOR_CHANNEL RMT_CHANNEL_1

#define RED_LED_TOP 40
#define RED_LED_BOT 35

#define BAT_PIN 18
