#define TOP_PHOTO_TRANSISTOR 11
#define BOTTOM_PHOTO_TRANSISTOR 12

#define LEFT_MOTOR GPIO_NUM_45
#define RIGHT_MOTOR GPIO_NUM_1

#define LEFT_MOTOR_CHANNEL RMT_CHANNEL_2
#define RIGHT_MOTOR_CHANNEL RMT_CHANNEL_1