#define TOP_PHOTO_TRANSISTOR 11
#define BOTTOM_PHOTO_TRANSISTOR 12

#define TOP_IR_PIN      41
#define BOTTOM_IR_PIN   42

#define LEFT_MOTOR_PIN GPIO_NUM_45
#define RIGHT_MOTOR_PIN GPIO_NUM_1

#define LEFT_MOTOR_CHANNEL RMT_CHANNEL_2
#define RIGHT_MOTOR_CHANNEL RMT_CHANNEL_1

#define BAT_PIN 18
